version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9
      - image: circleci/postgres:9.6.9-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
