version: 2.1
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9
        environment:
          MIX_ENV: test
      - image: circleci/postgres:11-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"
      - run: mix ecto.create
      - run: mix test
      - store_test_results:
          path: _build/test/lib/mj
  dialyzer:
    docker:
      - image: circleci/elixir:1.9
        environment:
          MIX_ENV: test
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
          - v1-dialyzer-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          - v1-dialyzer-cache-{{ .Branch }}
          - v1-dialyzer-cache
      - run: mix dialyzer --halt-exit-status
      - save_cache:
          key: v1-dialyzer-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - ~/.mix
            - _build
      - save_cache:
          key: v1-dialyzer-cache-{{ .Branch }}
          paths:
            - ~/.mix
            - _build
      - save_cache:
          key: v1-dialyzer-cache
          paths:
            - ~/.mix
            - _build
workflows:
  build-test-and-deploy:
    jobs:
      - build
      - dialyzer
