apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mj
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mj
    spec:
      containers:
        - name: mj
          image: mj:local
          imagePullPolicy: Never
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RELEASE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: releaseCookie
            - name: RELEASE_NODE
              value: "mj@$(POD_IP)"
            - name: RELEASE_DISTRIBUTION
              value: "name"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: secretKeyBase
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: databaseUrl
