apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  releaseCookie: cookie-cookie-cookie
  secretKeyBase: secret-secret-secret
  databaseUrl: ecto://postgres:postgres@localhost:5432
